#Nombre del workflow
name: Deploy to server

# Evento que dispara el workflow
on: push

# Definición de los jobs
jobs:
    first-jobs:
        runs-on: ubuntu-latest

        # Pasos a seguir en el job
        steps:
            - name: Hola Mundo
              run: echo "¡Hola, mundo! Este es un workflow de GitHub Actions."

    second-job:
        if: ${{ github.ref == 'refs/heads/master' }}  # Este job solo se ejecuta si el push es a la rama main
        needs: first-jobs  # Este job depende del primero
        runs-on: ubuntu-latest

        # Pasos a seguir en el job
        steps:
            - name: Hola Mundo
              run: echo "¡Hola, mundo 2!"

            